# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.3a2.dev10+gb13824d.d20221118'
__version_tuple__ = version_tuple = (0, 0, 3, 'dev10', 'gb13824d.d20221118')
